const state={data:null,query:""};const $=id=>document.getElementById(id);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function status(t,e=false){$("status").textContent=t;$("status").style.color=e?"var(--danger)":"var(--muted)"}
$("extractForm").onsubmit=async e=>{e.preventDefault();const url=$("url").value.trim();if(!/^https?:\/\//i.test(url)){status("Enter a complete http:// or https:// URL.",true);return}status("Extracting page data…");const btn=$("extractForm").querySelector("button");btn.disabled=true;try{const r=await fetch("/api/extract?url="+encodeURIComponent(url));const d=await r.json();if(!r.ok)throw Error(d.detail||"Extraction failed.");state.data=d;state.query="";$("search").value="";render(d);status(`Extracted ${d.summary.headings+d.summary.links+d.summary.images} items.`);$("results").scrollIntoView({behavior:"smooth"})}catch(err){status(err.message||"Extraction failed.",true)}finally{btn.disabled=false}};
function render(d){$("empty").hidden=true;$("data").hidden=false;$("resultTitle").textContent=d.title||"Untitled page";$("headingCount").textContent=d.summary.headings;$("linkCount").textContent=d.summary.links;$("imageCount").textContent=d.summary.images;$("metaCount").textContent=d.summary.metadata;$("json").disabled=false;$("csv").disabled=false;renderAll()}
function renderAll(){const d=state.data;if(!d)return;const q=state.query.toLowerCase();$("pageInfo").innerHTML=`<div class="info-row"><span>URL</span><a href="${esc(d.url)}" target="_blank" rel="noopener">${esc(d.url)}</a></div><div class="info-row"><span>Title</span><span>${esc(d.title||"—")}</span></div><div class="info-row"><span>Description</span><span>${esc(d.description||"—")}</span></div>`;const h=d.headings.filter(x=>x.text.toLowerCase().includes(q));const l=d.links.filter(x=>(x.text+" "+x.url).toLowerCase().includes(q));const im=d.images.filter(x=>(x.alt+" "+x.url).toLowerCase().includes(q));const m=d.metadata.filter(x=>(x.name+" "+x.content).toLowerCase().includes(q));$("headings").innerHTML=box(h.map(x=>`<div class="item"><strong>${esc(x.level.toUpperCase())}</strong> ${esc(x.text)}</div>`));$("links").innerHTML=box(l.map(x=>`<div class="item"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.text)}</a><span class="muted">${esc(x.url)}</span></div>`));$("images").innerHTML=box(im.map(x=>`<div class="image-item"><img src="${esc(x.url)}" alt="" loading="lazy" onerror="this.style.display='none'"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.alt||x.url)}</a></div>`));$("metadata").innerHTML=box(m.map(x=>`<div class="item"><strong>${esc(x.name)}</strong><span class="muted">${esc(x.content)}</span></div>`))}
function box(a){return a.length?`<div class="scrollbox">${a.join("")}</div>`:'<p class="empty-small">No matching data.</p>'}
$("search").oninput=e=>{state.query=e.target.value;renderAll()};
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$("json").onclick=()=>download("scrapely-data.json",JSON.stringify(state.data,null,2),"application/json");
$("csv").onclick=()=>{const d=state.data,r=[["type","name","value"],["page","title",d.title],...d.headings.map(x=>["heading",x.level,x.text]),...d.links.map(x=>["link",x.text,x.url]),...d.images.map(x=>["image",x.alt,x.url]),...d.metadata.map(x=>["metadata",x.name,x.content])];download("scrapely-data.csv",r.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),"text/csv")};
$("theme").onclick=()=>{document.body.classList.toggle("dark");const d=document.body.classList.contains("dark");localStorage.setItem("scrapely_theme",d?"dark":"light");$("theme").textContent=d?"☀":"☾"};if(localStorage.getItem("scrapely_theme")==="dark"){document.body.classList.add("dark");$("theme").textContent="☀"}